package br.univali.ui.paineis;

import br.univali.bd.ComunicacaoBD;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael F
 */
public class painelVerMidias extends javax.swing.JPanel {

    /**
     * Creates new form painelVerMidias
     */
    public painelVerMidias() throws Exception{
        initComponents();
        configurarTabela();
        
        popularTabela();
        criarDicaPesquisa();
    }
    private void configurarTabela(){
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setDefaultEditor(Object.class, null);
        tabela.setOpaque(true);
        tabela.setFillsViewportHeight(true);
        tabela.setBackground(Color.GRAY);
        tabela.setSelectionBackground(Color.darkGray);
    }
    
    private void criarDicaPesquisa(){
        txtBusca.setText("Pesquisar...");
        txtBusca.setForeground(Color.GRAY);
        txtBusca.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if(txtBusca.getText().equals("Pesquisar...")){
                    txtBusca.setText("");
                    txtBusca.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if(txtBusca.getText().isEmpty()){
                    txtBusca.setText("");
                    txtBusca.setForeground(Color.GRAY);
                    txtBusca.setText("Pesquisar...");
                }
            }
        });
    }
    
    private void popularTabela() throws Exception{
        tabela.setModel(ComunicacaoBD.getEntretenimentos());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnDeletar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtBusca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        tabela.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(255, 255, 255));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.setToolTipText("");
        tabela.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabela);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.BorderLayout());

        txtBusca.setEditable(false);
        txtBusca.setBackground(new java.awt.Color(60, 60, 60));
        txtBusca.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        txtBusca.setToolTipText("Título para pesquisar");
        txtBusca.setPreferredSize(new java.awt.Dimension(150, 25));
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaKeyTyped(evt);
            }
        });
        jPanel2.add(txtBusca, java.awt.BorderLayout.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/ressources/busca.png"))); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        try {
//            ComunicacaoBD.deletar(tabela.getSelectedRow());
            JOptionPane.showConfirmDialog(this, "Realmente deseja deletar a midia selecionada?");
            popularTabela();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyTyped
        try {
            tabela.setModel(ComunicacaoBD.getEntretenimentos(this.txtBusca.getText()));
        } catch (Exception ex) {
            Logger.getLogger(painelVerMidias.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscaKeyTyped
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
